import { AuthProvider } from '@/contexts/AuthContext'
import './globals.css'
import { ReactNode } from 'react'

export const metadata = {
  title: 'Controle de Convênios',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
